POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk3MTE0NTUsInVzZXJJZCI6MX0._Y4tXAiVCfe3UUpf7u9F-ReoMSWJS7EMvWgfDnoJ8sE

{
  "name": "Test event",
  "description": "Test even!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"

}